### ISSUE TITLE
Autocomplete information for functions is often less than useful due to ellipsis.

### ISSUE THREAD

**Issue by james-lawrence** [joefitzgerald/go-plus#504]
Not sure if this is a goplus issue or the underlying tool that goplus uses for perform autocomplete.
But for functions oftentimes it just ellipsis's out the return values of the function when trying to write code this can be very frustrating.

1) you can't tell how many values are going to be returned.
2) can't tell the types of the return value.

It'd be nice if we could have more details displayed.

**Comment by joefitzgerald** [comment]
I agree, this also bugs me. It is a behavior of autocomplete-plus, and is exacerbated at larger font sizes. @simurai it would be nice to modify the ac+ suggestion list so it is greedy about width when truncation might otherwise occur...

**Comment by simurai** [comment]
This came already up in https://github.com/atom/autocomplete-plus/pull/729. But it's hard to decide the widths of the columns because each language might use them differently. 

You can paste the following into your `styles.less` and then try to tweak the numbers to give more priority to a certain column.

```less
autocomplete-suggestion-list {
  // remove fixed width
  &.select-list.popover-list {
    max-width: none;
    width: auto !important;
  }
  
  // set width for each column
  .left-label { max-width: 300px; }
  .word { max-width: 500px; } // 500px by default
  .right-label { max-width: 500px; } // 150px by default 
}
```

Would actually be neat if you could resize the columns.
